# basic
input: [title, key, placeholder, defaultValue, rules, linkage]
select: [title, key, placeholder, options, rules, linkage]
number: [title, key, rules, linkage]
radio-group: [title, key, options, rules, linkage]
checkbox-group: [title, key, options, rules, linkage]
checkbox: [title, key, rules, linkage]
switch: [title, key, rules, linkage]
textarea: [title, key, placeholder, defaultValue, rules, linkage]
upload: [title, key, rules, linkage]

# date
date: [title, key, rules, linkage]
date-range: [title, key, rules, linkage]
time: [title, key, rules, linkage]
time-range: [title, key, rules, linkage]
date-time: [title, key, rules, linkage]
date-time-range: [title, key, rules, linkage]

# advance
dynamic: [title, key, rules, linkage]
view: [title, key, rules, linkage]