# basic
input:
- title
- key
- placeholder
- defaultValue
- type: icon
  title: 前置图标
  key: prefixIcon
- type: icon
  title: 后置图标
  key: suffixIcon
- disabled
- readonly
- clearable
- type: switch
  title: 密码框
  key: showPassword
- type: switch
  title: 限制文本长度
  key: showWordLimit
- type: number
  title: 最大长度
  defaultValue: 10
  key: maxlength
  linkage:
    type: shown
    condition: this.showWordLimit && !this.showPassword
- rules
- linkage
select: [title, key, placeholder, options, rules, linkage]
number:
- title
- key
- type: number
  title: 默认值
  key: defaultValue
- type: number
  title: 步长
  key: step
- type: number
  title: 精度
  key: precision
- type: select
  title: 样式
  key: controlsPosition
  options: between:按钮在两侧|right:按钮在右侧
  defaultValue: between
- disabled
- rules
- linkage
radio-group: [title, key, options, rules, linkage]
checkbox-group: [title, key, options, rules, linkage]
checkbox: [title, key, rules, linkage]
switch: [title, key, rules, linkage]
textarea:
- title
- key
- placeholder
- defaultValue
- disabled
- readonly
- type: switch
  title: 限制文本长度
  key: showWordLimit
- type: number
  title: 最大长度
  defaultValue: 100
  key: maxlength
  linkage:
    type: shown
    condition: this.showWordLimit
- rules
- linkage
upload: [title, key, rules, linkage]

# date
date: [title, key, rules, linkage]
date-range: [title, key, rules, linkage]
time: [title, key, rules, linkage]
time-range: [title, key, rules, linkage]
date-time: [title, key, rules, linkage]
date-time-range: [title, key, rules, linkage]

# advance
dynamic: [title, key, rules, linkage]
view: [title, key, rules, linkage]