# basic
input: [title, key, placeholder, defaultValue, rules, linkage]
select: [title, key, placeholder, options]
number: [title, key]
radio-group: [title, key, options]
checkbox-group: [title, key, options]
checkbox: [title, key]
switch: [title, key]
textarea: [title, key, placeholder, defaultValue]
upload: [title, key]

# date
date: [title, key]
date-range: [title, key]
time: [title, key]
time-range: [title, key]
date-time: [title, key]
date-time-range: [title, key]

# advance
dynamic: [title, key]
view: [title, key]