title:
  type: input
  title: 标题
  key: title
key:
  type: input
  title: 字段索引
  key: key
placeholder:
  type: input
  title: 占位内容
  key: placeholder
defaultValue:
  type: input
  title: 默认值
  key: defaultValue
disabled:
  type: switch
  title: 禁用
  key: disabled
readonly:
  type: switch
  title: 只读
  key: readonly
clearable:
  type: switch
  title: 可清空
  key: clearable
options:
  type: view
  title: 选项配置
  components:
  - type: radio-group
    title: 选项类型
    key: optionType
    options: local:本地数据|remote:远程数据
    defaultValue: local
  - type: dynamic
    title: 选项
    key: options
    useView: true
    components:
    - type: input
      key: key
      title: 选项值
    - type: input
      key: value
      title: 显示名
    linkage:
      type: shown
      condition: this.optionType==='local'
  - type: input
    title: 接口地址
    key: url
    linkage:
      type: shown
      condition: this.optionType==='remote'
rules:
  type: dynamic
  title: 规则设置
  key: rules
  useView: true
  components:
  - type: select
    title: 规则类型
    key: type
    options:
    - key: required
      value: 必需
    - key: number
      value: 数字校验
  - type: input
    title: 错误信息
    key: message
  - type: number
    title: 最大值
    key: max
    linkage:
      type: shown
      condition: this.type==='number'
linkage:
  type: view
  title: 联动设置
  key: linkage
  components:
  - type: select
    title: 联动类型
    key: type
    options:
    - key: disabled
      value: 禁用
    - key: enabled
      value: 可用
    - key: hidden
      value: 隐藏
    - key: shown
      value: 显示
  - type: textarea
    title: 条件设置
    key: condition
  # - type: dynamic
  #   title: 条件设置
  #   key: condition
  #   useView: true
  #   components:
  #   - type: select
  #     title: 字段
  #     key: field
  #     options: []
  #   - type: select
  #     title: 条件
  #     key: 'on'
  #     options: "=|>|>=|<|<=|!="
  #   - type: input
  #     title: 值
  #     key: value
