components:
# type|title|key|defaultValue|tag|...props
- input|单行文本|||基础组件|basic|placeholder|defaultValue
- number|数字|||基础组件|basic|placeholder|defaultValueNumber
- textarea|多行文本|||基础组件|basic|placeholder|defaultValue

- type: select|下拉框|||基础组件|basic|placeholder|defaultValue|options
  options: option1:选项1|option2:选项2
- type: checkbox-group|复选框|||基础组件|basic|defaultValueArray
  options: option1:选项1|option2:选项2
- type: radio-group|单选框|||基础组件|basic|defaultValue
  options: option1:选项1|option2:选项2

- switch|开关|||基础组件|basic
- date|日期|||日期时间组件|basic
- date-range|日期范围|||日期时间组件|basic
- time|时间|||日期时间组件|basic
- time-range|时间范围|||日期时间组件|basic
- date-time|日期时间|||日期时间组件|basic
- date-time-range|日期时间范围|||日期时间组件|basic

- type: dynamic
  title: 动态组件
  components:
  - type: input
    key: key
    placeholder: key
  - type: input
    key: value
    placeholder: value
  tag: 高级组件
  props:
  - basic
- type: view
  title: 视图组件
  components:
  - type: input
    key: key
    placeholder: key
  - type: input
    key: value
    placeholder: value
  tag: 高级组件
  props:
  - basic

form:
- input|标签宽度|labelWidth|auto  
- type: select|对齐方式|labelPosition|right
  options: left:左对齐|right:右对齐|top:顶部对齐

reference:
- input|标题|title||basic
- input|字段索引|key||basic
- input|站位内容|placeholder||placeholder
- input|默认值|defaultValue||defaultValue
- checkbox-group|默认值|defaultValue||defaultValueArray
- number|默认值|defaultValue||defaultValueNumber
- type: dynamic|选项|options||options
  components:
  - type: input||key
    placeholder: key
  - type: input||value
    placeholder: value
