components:
- type: input
  title: 单行文本
  tag: 基础组件
  props: [basic, placeholder, defaultValue, rules, linkage]
- type: number
  title: 数字
  tag: 基础组件
  props: [basic, placeholder, defaultValueNumber]
- type: textarea
  title: 多行文本
  tag: 基础组件
  props: [basic, placeholder, defaultValue]
- type: select
  title: 下拉框
  options:
  - key: option1
    value: 选项1
  - key: option2
    value: 选项2
  tag: 基础组件
  props: [basic, placeholder, defaultValue, options]
- type: checkbox-group
  title: 复选框
  options:
  - key: option1
    value: 选项1
  - key: option2
    value: 选项2
  tag: 基础组件
  props: [basic, defaultValueArray]
- type: radio-group
  title: 单选框
  options:
  - key: option1
    value: 选项1
  - key: option2
    value: 选项2
  tag: 基础组件
  props: [basic, defaultValue]
- type: switch
  title: 开关
  tag: 基础组件
  props: [basic]
- type: date
  title: 日期
  tag: 日期时间组件
  props: [basic]
- type: date-range
  title: 日期范围
  tag: 日期时间组件
  props: [basic]
- type: time
  title: 时间
  tag: 日期时间组件
  props: [basic]
- type: time-range
  title: 时间范围
  tag: 日期时间组件
  props: [basic]
- type: date-time
  title: 日期时间
  tag: 日期时间组件
  props: [basic]
- type: date-time-range
  title: 日期时间范围
  tag: 日期时间组件
  props: [basic]
- type: dynamic
  title: 动态组件
  components:
  - type: input
    key: key
    placeholder: key
  - type: input
    key: value
    placeholder: value
  tag: 高级组件
  props: [basic]
- type: view
  title: 视图组件
  components:
  - type: input
    key: key
    placeholder: key
  - type: input
    key: value
    placeholder: value
  tag: 高级组件
  props: [basic]

form:
- type: select
  title: 组件尺寸
  key: size
  options:
  - key: medium
    value: 大
  - key: small
    value: 中
  - key: mini
    value: 小
- type: switch
  title: 行内布局
  key: inline
  defaultValue: false
- type: input
  title: 标签宽度
  key: labelWidth
  defaultValue: auto
- type: select
  title: 对齐方式
  key: labelPosition
  defaultValue: right
  options:
  - key: left
    value: 左对齐
  - key: right
    value: 右对齐
  - key: top
    value: 顶部对齐
reference:
- type: input
  title: 标题
  key: title
  tag: basic
- type: input
  title: 字段索引
  key: key
  tag: basic

- type: dynamic
  title: 规则设置
  key: rules
  components:
  - type: select
    title: 规则类型
    key: type
    options:
    - key: required
      value: 必需
    - key: number
      value: 数字校验
  - type: input
    title: 错误信息
    key: message
  - type: number
    title: 最大值
    key: max
    linkage:
      type: hidden
      condition: type==='number'
  tag: rules

- type: view
  title: 联动设置
  components:
  - type: select
    title: 联动类型
    key: type
    options:
    - key: disabled
      value: 禁用
    - key: enabled
      value: 可用
    - key: hidden
      value: 隐藏
    - key: shown
      value: 显示
  - type: textarea
    title: 条件设置
    key: condition
  tag: linkage

- type: input
  title: 占位内容
  key: placeholder
  tag: placeholder
- type: input
  title: 默认值
  key: defaultValue
  tag: defaultValue
- type: checkbox-group
  title: 默认值
  key: defaultValue
  tag: defaultValueArray
- type: number
  title: 默认值
  key: defaultValue
  tag: defaultValueNumber
- type: dynamic
  title: 选项
  key: options
  components:
  - type: input
    key: key
    placeholder: key
  - type: input
    key: value
    placeholder: value
  tag: options